import React, { useEffect, useState } from "react";

function useIsAuthenticated() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);

  useEffect(() => {
    //sessionID = 6qry4l9volwsynczwpexu46jv7qa9gk6
    //refreshToken = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDExYjU1ODFkYjI0YjViYTUxN2U5ZWFjNjliNTRkYiIsInBsYXllcklkIjoic2NfMTEwN2EyN2MtZWNmZi00YTc3LWI5NzUtODBjMzFjMzQyMjk3Iiwibmlja25hbWUiOiJxdWFubTEiLCJpYXQiOjE3MjgxOTQ2NzcsImV4cCI6MTcyODQ1Mzg3NywiaXNzIjoid3dlLXdlYi1wb3J0YWwtc2VydmVyIn0.suhuOpFk1Lj9PNYrpxwCixYjEn-A4ENOyoNMBacev8KsyNS1QdQQL3vZv32MKOKhDDu_RdO_UYPJhffLnVX7mA
    //accessToken_dev = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InF1YW5tMSIsInVzZXJJZCI6ImM0MTFiNTU4MWRiMjRiNWJhNTE3ZTllYWM2OWI1NGRiIiwicGxheWVySWQiOiJVSW1tQUJ1diIsImZiSWQiOiJudWxsIiwic2NvcGVseUlkIjoic2NfMTEwN2EyN2MtZWNmZi00YTc3LWI5NzUtODBjMzFjMzQyMjk3Iiwibm9uY2UiOiJoOWd3bGppYnRlNnY2ZDl1MXhyYTlpNTJ1NmJqazhpdSIsImVtYWlsIjoiIiwibmV3VXNlciI6bnVsbCwic2Vzc2lvblRva2VuIjoiNnFyeTRsOXZvbHdzeW5jendwZXh1NDZqdjdxYTlnazYiLCJwcm9maWxlSW1nIjoiaHR0cHM6Ly9zdGF0aWMud3dlY2hhbXBpb25zLmNvbS91c2VyX2ltYWdlcy9jNDExYjU1ODFkYjI0YjViYTUxN2U5ZWFjNjliNTRkYi5qcGciLCJkZXZpY2VUb2tlbiI6IjZhNjZkNWVjLWRhYmItNDczNC1iOTA3LWVlNWRmNWY3ODhmOCIsInRlbXBvcmFyeU5pY2tuYW1lIjpudWxsLCJhbGlhcyI6InNjXzExMDdhMjdjLWVjZmYtNGE3Ny1iOTc1LTgwYzMxYzM0MjI5NyIsImlhdCI6MTcyODE5NDY3NywiZXhwIjoxNzI4NDEwNjc3LCJpc3MiOiJ3d2Utd2ViLXBvcnRhbC1zZXJ2ZXIifQ.4E1GLBwP68SCP7SqrTJi7sYJxuq4dH4JNCRut6AsCrxmiKmDR73z6qyPM3qNvX0MuUkNYn-1qDz_jhfAw_znYQ
    const getAuthenticated = window.localStorage.getItem("refreshToken");
    setIsAuthenticated(!!getAuthenticated);
  }, []);
  return { isAuthenticated };
}

export default useIsAuthenticated;
